import { supabase } from '../lib/supabase';

export interface BankTransferPaymentData {
  orderReference: string;
  customerEmail: string;
  customerName: string;
  customerPhone: string;
  customerAddress: {
    address: string;
    city: string;
    state: string;
    postcode: string;
    country: string;
  };
  cartItems: Array<{
    id: string;
    name: string;
    price: number;
    quantity: number;
    image?: string;
  }>;
  subtotal: number;
  shipping: number;
  tax: number;
  totalAmount: number;
  currency?: string;
  discountCode?: string | null;
  discountAmount?: number;
  /**
   * UUID generated by the client and reused across retries of the SAME submit
   * attempt. The server returns the existing tracking_id without writing if
   * it has already seen this key. Generate ONCE per "place order" click — not
   * per retry — so legitimate retries collapse into one row.
   */
  idempotencyKey?: string;
}

export interface ServerTotalsResult {
  /** True when the server returned its own recomputed totals (post-migration). */
  available: boolean;
  serverTotal?: number;
  serverSubtotal?: number;
  serverShipping?: number;
  serverTax?: number;
  serverDiscount?: number;
  /** True when the server detected the client total differed by > 1¢. */
  tamperDetected?: boolean;
  clientTotalWas?: number;
}

/**
 * Create or update payment tracking record when customer checks out
 */
export async function createPaymentTracking(
  data: BankTransferPaymentData
): Promise<{
  success: boolean;
  trackingId?: string;
  error?: string;
  serverTotals?: ServerTotalsResult;
}> {
  try {
    if (!supabase) {
      return { success: false, error: 'Supabase client not initialized' };
    }

    // Guard against accidental overwrites: if a record with this order reference
    // already exists and is past the pending state, don't upsert over it.
    const { data: existing } = await supabase
      .from('payment_tracking')
      .select('id, payment_status')
      .eq('order_reference', data.orderReference)
      .maybeSingle();

    if (existing && existing.payment_status !== 'pending') {
      return {
        success: false,
        error: `Order ${data.orderReference} already exists with status "${existing.payment_status}".`,
      };
    }

    const { data: result, error } = await supabase.rpc('upsert_payment_tracking', {
      p_order_reference: data.orderReference,
      p_customer_email: data.customerEmail,
      p_customer_name: data.customerName,
      p_customer_phone: data.customerPhone,
      p_customer_address: data.customerAddress,
      p_cart_items: data.cartItems,
      p_subtotal: data.subtotal,
      p_shipping: data.shipping,
      p_tax: data.tax,
      p_total_amount: data.totalAmount,
      p_currency: data.currency || 'AUD',
      p_discount_code: data.discountCode ?? null,
      p_discount_amount: data.discountAmount ?? 0,
      // Pre-migration servers ignore the extra arg — RPC default is NULL.
      p_idempotency_key: data.idempotencyKey ?? null,
    });

    if (error) {
      console.error('Error creating payment tracking:', error);
      return { success: false, error: error.message };
    }

    // Surface the server's recomputed totals when the new migration is live.
    // Pre-migration the RPC returns only { success, tracking_id } so these
    // fields will be `undefined` and ServerTotalsResult.available stays false.
    const r = result as Record<string, unknown> | null;
    const serverTotal = typeof r?.server_total === 'number' ? r.server_total : undefined;
    const serverTotals: ServerTotalsResult = {
      available: typeof serverTotal === 'number',
      serverTotal,
      serverSubtotal: typeof r?.server_subtotal === 'number' ? r.server_subtotal : undefined,
      serverShipping: typeof r?.server_shipping === 'number' ? r.server_shipping : undefined,
      serverTax: typeof r?.server_tax === 'number' ? r.server_tax : undefined,
      serverDiscount: typeof r?.server_discount === 'number' ? r.server_discount : undefined,
      tamperDetected: r?.tamper_detected === true,
      clientTotalWas: typeof r?.client_total_was === 'number' ? r.client_total_was : undefined,
    };

    return {
      success: result?.success || false,
      trackingId: result?.tracking_id,
      serverTotals,
    };
  } catch (err) {
    console.error('Exception creating payment tracking:', err);
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Unknown error',
    };
  }
}

/**
 * Mark that customer clicked Payment button and viewed instructions
 */
export async function markPaymentInstructionsViewed(
  orderReference: string
): Promise<{ success: boolean; error?: string }> {
  try {
    if (!supabase) {
      return { success: false, error: 'Supabase client not initialized' };
    }
    const { data: result, error } = await supabase.rpc('mark_payment_instructions_viewed', {
      p_order_reference: orderReference,
    });

    if (error) {
      console.error('Error marking payment viewed:', error);
      return { success: false, error: error.message };
    }

    return { success: result?.success || false };
  } catch (err) {
    console.error('Exception marking payment viewed:', err);
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Unknown error',
    };
  }
}

export interface OrderStatusLookupResult {
  success: boolean;
  error?: string;
  order?: {
    orderReference: string;
    paymentStatus: string;
    totalAmount: number;
    currency: string;
    createdAt: string;
    updatedAt: string;
    paymentViewedAt: string | null;
    paymentCompletedAt: string | null;
  };
}

/**
 * Public customer-facing lookup. Requires the caller to provide BOTH the
 * order reference and the customer email — anyone with just the ref can't
 * see someone else's order. Backed by `lookup_order_by_ref_and_email`
 * (migration 20260517160000).
 *
 * Returns a single generic 'Order not found' error for any mismatch so the
 * caller can't tell which field was wrong.
 */
export async function lookupOrderStatus(
  orderReference: string,
  customerEmail: string
): Promise<OrderStatusLookupResult> {
  if (!supabase) return { success: false, error: 'Order lookup unavailable.' };
  const ref = orderReference.trim();
  const email = customerEmail.trim();
  if (!ref || !email) {
    return { success: false, error: 'Order reference and email are required.' };
  }
  try {
    const { data, error } = await supabase.rpc('lookup_order_by_ref_and_email', {
      p_order_reference: ref,
      p_customer_email: email,
    });
    if (error) {
      // PGRST202 / 42883: function not yet deployed — degrade gracefully.
      if (error.code === '42883' || error.code === 'PGRST202') {
        return {
          success: false,
          error: 'Order lookup is not enabled on this site yet. Please email us instead.',
        };
      }
      return { success: false, error: 'Could not look up your order. Please try again.' };
    }
    const r = data as Record<string, unknown> | null;
    if (!r?.success) {
      return { success: false, error: (r?.error as string) ?? 'Order not found' };
    }
    return {
      success: true,
      order: {
        orderReference: String(r.order_reference ?? ref),
        paymentStatus: String(r.payment_status ?? 'pending'),
        totalAmount: Number(r.total_amount ?? 0),
        currency: String(r.currency ?? 'AUD'),
        createdAt: String(r.created_at ?? ''),
        updatedAt: String(r.updated_at ?? ''),
        paymentViewedAt: typeof r.payment_viewed_at === 'string' ? r.payment_viewed_at : null,
        paymentCompletedAt: typeof r.payment_completed_at === 'string' ? r.payment_completed_at : null,
      },
    };
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : 'Lookup failed' };
  }
}

/**
 * Get payment tracking info by order reference
 */
export async function getPaymentTrackingByReference(
  orderReference: string
): Promise<{
  success: boolean;
  data?: {
    orderReference: string;
    customerName: string;
    totalAmount: number;
    currency: string;
    paymentStatus: string;
    paymentViewedAt: string | null;
    createdAt: string;
  };
  error?: string;
}> {
  try {
    if (!supabase) {
      return { success: false, error: 'Supabase client not initialized' };
    }
    const { data: result, error } = await supabase.rpc('get_payment_tracking_by_reference', {
      p_order_reference: orderReference,
    });

    if (error) {
      console.error('Error getting payment tracking:', error);
      return { success: false, error: error.message };
    }

    if (!result?.success) {
      return { success: false, error: result?.error || 'Order not found' };
    }

    return {
      success: true,
      data: {
        orderReference: result.order_reference,
        customerName: result.customer_name,
        totalAmount: result.total_amount,
        currency: result.currency,
        paymentStatus: result.payment_status,
        paymentViewedAt: result.payment_viewed_at,
        createdAt: result.created_at,
      },
    };
  } catch (err) {
    console.error('Exception getting payment tracking:', err);
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Unknown error',
    };
  }
}
